name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to crates.io
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Cargo.toml version
        run: |
          cargo set-version "${{ steps.get_version.outputs.RELEASE_VERSION }}"

      - name: Commit and push changes
        run: |
          git add Cargo.toml
          git commit -m '[Github Actions] update version to ${{ steps.get_version.outputs.RELEASE_VERSION }}'
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
